name: "Deploy TestApp Commands"

on:
  push:
    tags:
      - "TestAppCommands/v*"

env:
  PROJECT_PATH: TestApp/TestApp/TestApp.csproj

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore packages
        run: dotnet restore "${{ env.PROJECT_PATH }}"

      - name: Build the project
        run: dotnet build "${{ env.PROJECT_PATH }}" -c Release --no-restore

      - name: Publish the project
        run: dotnet publish "${{ env.PROJECT_PATH }}" -c Release --self-contained -r win-x64

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          pattern: TestApp/TestApp/bin/Release/net6.0-windows/publish/win-x64/*.exe
          release-url: ${{ steps.create_release.outputs.upload_url }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_ID: ${{ steps.create_release.outputs.id }}
     
