name: "Deploy TestApp Commands"

on:
  push:
    tags:
      - "TestAppCommands/v*"

env:
  PROJECT_PATH: TestApp/TestApp/TestApp.csproj

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - run: dotnet restore "${{ env.PROJECT_PATH }}"

      - run: dotnet build "${{ env.PROJECT_PATH }}" -c Release --no-restore

      - run: dotnet publish "${{ env.PROJECT_PATH }}" -c Release --self-contained -r win-x64 

      - name: Create Release
        id: create_release

        uses: actions/create_release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./publish/TestApp.exe
          asset_name: TestApp.exe
          asset_content_type: application/octet-stream
